package GUI;

import Catalog.Product;
import Catalog.Stock;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Jose Ortiz
 *
 * This class extends JPanel and contains the functionality to show the products
 * on the catalog and will have a button to add a selected product to the cart
 * list.
 */
public class InventoryPanel extends javax.swing.JPanel {

    /**
     * Only contains functionality used on the Inventory Panel
     */
    Stock catalog;
    ArrayList<Product> products;
    DefaultListModel listModel;
    private PostGUI masterPost; //reference to the parent master GUI
    static int productSelected = 0; // keep track of the index selected 

    /**
     * Constructor
     *
     * @param _currentPost connection the the main Post frame (client)
     * @throws RemoteException
     */
    public InventoryPanel(PostGUI _currentPost) throws RemoteException {
        masterPost = _currentPost;
        initComponents();
        // initializes the catalog sent from the server
        initCatalog();

    }

    /**
     * Initializes the catalog sent from the server and load its products on the
     * inventory list
     */
    public void initCatalog() {
        listModel = new DefaultListModel();
        catalog = masterPost.getLocalCatalog();
        products = catalog.getProductsFromStock();
        for (Product product : products) {
            listModel.addElement(product.productReaderToString());
        }
        inventoryList.setModel(listModel);
        inventoryList.addMouseListener(mouseListener);
        inventoryList.setFont(new Font("monospaced", Font.PLAIN, 10));
    }

    /**
     * Gets the container list where the products are displayed
     *
     * @return a JList Object
     */
    public JList getList() {
        return this.inventoryList;
    }

    /**
     * Event listener to select a product.
     */
    MouseListener mouseListener = new MouseAdapter() {
        public void mouseClicked(MouseEvent mouseEvent) {
            JList theList = (JList) mouseEvent.getSource();
            if (mouseEvent.getClickCount() == 1) {
                int index = theList.getSelectedIndex();
                if (index >= 0) {
                    Object o = theList.getModel().getElementAt(index);
                    productSelected = index;

                }
            }
            if (mouseEvent.getClickCount() == 2) {
                int index = theList.getSelectedIndex();
                if (index >= 0) {
                    Object o = theList.getModel().getElementAt(index);
                    productSelected = index;
                    masterPost.handleDoubleClickedProduct();

                }
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inventoryListScrollPane = new javax.swing.JScrollPane();
        inventoryList = new javax.swing.JList();
        itemNameLabel = new javax.swing.JLabel();
        unitPriceLabel = new javax.swing.JLabel();
        UpcLabel = new javax.swing.JLabel();
        addToCartBtn = new javax.swing.JButton();
        quantitySelector = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(212, 212, 212));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setForeground(new java.awt.Color(212, 212, 212));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INVENTORY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18))); // NOI18N

        inventoryList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        inventoryListScrollPane.setViewportView(inventoryList);

        itemNameLabel.setText("UPC");

        unitPriceLabel.setText("Item");

        UpcLabel.setText("Unit_Price");

        addToCartBtn.setText("Add To Cart");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
                addToCartButtonHandler(evt);
            }
        });

        quantitySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        quantitySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitySelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(unitPriceLabel)
                .addGap(82, 82, 82)
                .addComponent(UpcLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemNameLabel)
                .addContainerGap(89, Short.MAX_VALUE))
            .addComponent(inventoryListScrollPane)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addToCartBtn)
                .addGap(36, 36, 36)
                .addComponent(quantitySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLabel)
                    .addComponent(unitPriceLabel)
                    .addComponent(UpcLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inventoryListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addToCartBtn)
                    .addComponent(quantitySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addToCartBtnActionPerformed
    /**
     * Click handler that add a product to the cart
     *
     * @param evt
     */
    private void addToCartButtonHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonHandler
        String quantity = (String) quantitySelector.getSelectedItem();
        Integer productQuantity = Integer.valueOf(quantity);
        masterPost.handleAddProduct(productSelected, productQuantity);
    }//GEN-LAST:event_addToCartButtonHandler

    private void quantitySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitySelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitySelectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UpcLabel;
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JList inventoryList;
    private javax.swing.JScrollPane inventoryListScrollPane;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> quantitySelector;
    private javax.swing.JLabel unitPriceLabel;
    // End of variables declaration//GEN-END:variables
}
